services:
  ginplayground:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ginplayground-server
    ports:
      - "8080:8080"
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_SSL_MODE: disable
      DATABASE_NAME: todo_app
      SSLROOTCERT: /
      SERVER_PORT: 8080
      GO_MODE: debug
      ALLOWED_ORIGINS: *
      JWT_SECRET: 9e7e07a6d1c7a1e8b45a3ab5600c5dde307478d847b708d02698b7c0c2373367
      TOKEN_DURATION_MINUTES: 5
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.2-alpine3.21
    container_name: postgres-todo-app
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo_app
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d todo_app" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db-data: